Adding Metaplex Core support
solana-foundation/explorer pull request #431
Opened 2024-12-27 21:50 UTC by blockiosaurus

2024-12-30 22:45 UTC, ngundotra commented
Thanks for all the hardwork here Keith! Can you provide some sample accounts & screenshots for me to validate?

There's some stuff to nit over, but want to get the big stuff done first.

2025-01-03 14:54 UTC, ngundotra commented
Okay the Asset renders great, but the Core collection's address causes the page to crash.

<img width="965" alt="Screenshot 2025-01-03 at 9 48 17 AM" src="https://github.com/user-attachments/assets/92550db1-a170-4b89-bd7e-21de2ee6e913" />

Can you help me fix this?

I want to write tests for this PR like the ones I added here https://github.com/solana-labs/explorer/blob/master/app/components/instruction/lighthouse/__tests__/LighthouseDetailsCard.test.tsx

In order to do this, I need some pages that render correctly. Then I can add tests, make sure things work the way we expect, and then provide feedback on code style etc.

FWIW on Asset, I think it would be better to render the Core /metadata section as an actual table instead of a JSON view. It's nicer to be able to hyperlink to owner/delegate etc. Wdyt?

<img width="1132" alt="Screenshot 2025-01-03 at 9 53 23 AM" src="https://github.com/user-attachments/assets/8ad8f8cf-cd26-46a9-a60e-e7989ed1d4d6" />

2025-02-11 17:17 UTC, blockiosaurus commented
Tests added. Wen merge

2025-02-11 18:26 UTC, ngundotra requested changes
Overall this looks great, very clean change. Thanks for the reminder ping on this.

Can you provide a few urls for me to test locally?

2025-02-11 18:26 UTC, ngundotra commented on app/address/[address]/core-metadata/page-client.tsx
> +// import { isTokenProgramData } from '@providers/accounts';
nit: remove

2025-02-11 18:26 UTC, ngundotra commented on app/address/[address]/core-metadata/page-client.tsx
> +    // onNotFound,
nit: remove

2025-02-11 18:26 UTC, ngundotra commented on app/address/[address]/core-metadata/page-client.tsx
> +    // const [json, setJson] = React.useState<any | null>(null);
nit: remove

2025-02-11 18:26 UTC, ngundotra commented on app/address/[address]/core-metadata/page-client.tsx
> +            return;
Can you use the normal ErrorCard here with a text error description?

2025-02-11 18:26 UTC, ngundotra commented on app/address/[address]/layout.tsx
> +        console.log("Core Account");
nit: remove

2025-02-11 18:26 UTC, ngundotra commented on app/address/[address]/layout.tsx
> +        if (!parsedData?.nftData?.metadata.uri && tokenInfo) {
did this recently stop working, or did the `nftData.metadata` payload change?

Not clear to me why this needs to be removed

2025-02-11 18:26 UTC, ngundotra commented on app/address/[address]/layout.tsx
> +                name: parsedData?.nftData?.json?.name ?? parsedData?.nftData.metadata.name,
same comment as above

2025-02-11 18:26 UTC, ngundotra commented on app/components/account/MetaplexNFTAttributesCard.tsx
> +            const response = await fetch(nftData.metadata.uri);
Can you rebase & use `getProxiedUri(nftData.metadata.uri)` here please?

2025-02-11 18:26 UTC, ngundotra commented on app/components/account/MetaplexNFTHeader.tsx
> +                        {metadata.name !== '' ? metadata.name : 'No NFT name was found'}
I'm not opposed to changing where this sources name from, but do you mind explaining rationale for this change & others that use `metadata` instead of `metadata.data`?

2025-02-11 18:26 UTC, ngundotra commented on app/components/account/mplCore/CoreAccountHeader.tsx
> +        return <div>Invalid Core Account</div>
Can you use ErrorCard here?

2025-02-11 18:59 UTC, blockiosaurus commented on app/address/[address]/layout.tsx
> +        if (!parsedData?.nftData?.metadata.uri && tokenInfo) {
The payload changed. This is using the up to date mpl-token-metadata API with better organization and representation of all fields.

2025-02-11 19:00 UTC, blockiosaurus commented on app/address/[address]/layout.tsx
> +                name: parsedData?.nftData?.json?.name ?? parsedData?.nftData.metadata.name,
Ditto. The SDK being relied on here is deprecated.

2025-02-11 19:00 UTC, blockiosaurus commented on app/components/account/MetaplexNFTHeader.tsx
> +                        {metadata.name !== '' ? metadata.name : 'No NFT name was found'}
Ditto

2025-02-11 19:04 UTC, ngundotra commented on app/address/[address]/layout.tsx
> +        if (!parsedData?.nftData?.metadata.uri && tokenInfo) {
Damn rip. Is there easy way to get a test for this in CI, that way I can monitor if API response schema changes?

2025-02-11 19:08 UTC, blockiosaurus commented on app/address/[address]/layout.tsx
> +        if (!parsedData?.nftData?.metadata.uri && tokenInfo) {
It's not an API response schema. It's the newer SDK versions we launched in 2023. It won't break unless you upgrade, which this PR handles.

2025-02-11 19:22 UTC, ngundotra commented on app/address/[address]/layout.tsx
> +        if (!parsedData?.nftData?.metadata.uri && tokenInfo) {
Sweet

2025-02-11 19:23 UTC, ngundotra commented
@blockiosaurus Also example tests for integration look like [this (lighthouse)](https://github.com/solana-foundation/explorer/blob/master/app/components/instruction/lighthouse/__tests__/LighthouseDetailsCard.test.tsx). 

The goal is to check expected layout of data so I don't have to remember what each card is supposed to look like

2025-02-11 19:51 UTC, blockiosaurus commented on app/components/account/MetaplexNFTAttributesCard.tsx
> +            const response = await fetch(nftData.metadata.uri);
Oh no I'm back in lockfile hell 😭 . Let me try and resolve some of the dep changes.

2025-02-11 22:27 UTC, blockiosaurus commented
OK, updated fixing the feedback. I've made some somewhat opinionated decisions on the best way to represent assets (TM and Core) that's very dev-focused, so let me know if you have a different perspective.

Collections to test with:
https://explorer-omega.vercel.app/address/J9UwCCvPASZirDhjXxJwBBttTUTQ1jknCDXxESiYhMQC/core-metadata
https://explorer-omega.vercel.app/address/kzna1NTTupDPh9sJtPan2CCwhsmcsXMmFoKayoa9zx6/core-metadata

Assets:
https://explorer-omega.vercel.app/address/5vEXoEtgeRGsspAujxSgxjKCLB7iXbcNckGuh8ukHT3z/core-metadata
https://explorer-omega.vercel.app/address/ADKzcdqtuY49RXZdCGuwxy6eZSyZ5ns6Lb6AByhGXdZa/core-metadata
https://explorer-omega.vercel.app/address/E4zYUeMpZMd1yEBtWoQiUbFjcqcm2J8586L5N5gxTdhS/core-metadata
https://explorer-omega.vercel.app/address/FkZSwiCTHMtKcu5mdkpRKPMPLkCiK8iJRrP1kyRTHrBh/core-metadata
https://explorer-omega.vercel.app/address/CBQWWZr9YadQmuU6jxRhsAmGu5aL9DcX4j4GpW1NkmzY/core-metadata

2025-02-12 14:22 UTC, ngundotra commented
For the collections - wouldn't it be better to just fix the incorrect compressed NFT tagging here?
<img width="1123" alt="Screenshot 2025-02-12 at 9 18 47 AM" src="https://github.com/user-attachments/assets/99729b57-b056-4834-9517-c1c96d45b5ee" />

I think those overview fields are more useful than what is shown here, which looks like default card:
<img width="1148" alt="Screenshot 2025-02-12 at 9 19 20 AM" src="https://github.com/user-attachments/assets/9e5bbfc3-6e6e-41f7-ab91-33c7fcb6e7e5" />

Normal assets look great.

2025-02-12 14:23 UTC, ngundotra commented on app/components/account/CoreMetadataCard.tsx
> +                    <ReactJson src={json} theme={'solarized'} style={{ padding: 25 }} />
nit: can you add `name={false}` as argument?

2025-02-12 17:46 UTC, blockiosaurus commented on app/components/account/CoreMetadataCard.tsx
> +                    <ReactJson src={json} theme={'solarized'} style={{ padding: 25 }} />
Done

2025-02-28 19:52 UTC, ngundotra commented
Hey @blockiosaurus I'm happy to review this, but you haven't addressed my last comment, nor have you added test, nor have you updated lint to pass CI.

Can you please address these items before requesting a review from me?

2025-03-01 08:26 UTC, blockiosaurus commented
Do you mean additional tests beyond the ones I've already added? It's hard to tell what you mean when no other plugin seems to have tests either 😅.

2025-03-01 08:29 UTC, blockiosaurus commented
Closing this PR until the Explorer team creates actual contribution guidelines and is ready to accept external contributions without constantly moving goalposts.

2025-03-01 08:29 UTC, closed without merging